### ISSUE TITLE
Still supported?

### ISSUE THREAD

**Issue by SantoDE** [erik5388/jquery.gracket.js#10]
Hey there,

I'm currently trying to get this to work with JQuery 1.9.1. Though, I can't get it to work sadly :( Do you know whether it's supposed to work with 1.9.1 or not?

My error is:

$("[data-gracket]").gracket();
SyntaxError: Unexpected token omessage: "Unexpected token o

**Comment by erik5388** [comment]
Still functional. Been focused on a newer version. I'll review the PR now.
