### ISSUE TITLE
Does not support 32 bracket size? 

### ISSUE THREAD

**Issue by Geczy** [erik5388/jquery.gracket.js#9]
Seems the code is hardcoded for only tournaments with 16 teams. Is that true?

**Comment by ddauto** [comment]
Hi,
It seems didn't supoort >=32 teams, I used below data and the layout broken too.
Is there anything need to be configure?
[
	[[{"name":"A","id":"A","seed":1},{"name":"B","id":"B","seed":2}]
	,[{"name":"C","id":"C","seed":3},{"name":"D","id":"D","seed":4}]
	,[{"name":"E","id":"E","seed":5},{"name":"F","id":"F","seed":6}]
	,[{"name":"G","id":"G","seed":7},{"name":"H","id":"H","seed":8}]
	,[{"name":"I","id":"I","seed":9},{"name":"J","id":"J","seed":10}]
	,[{"name":"K","id":"K","seed":11},{"name":"L","id":"0L","seed":12}]
	,[{"name":"M","id":"M","seed":13},{"name":"N","id":"N","seed":14}]
	,[{"name":"O","id":"O","seed":15},{"name":"P","id":"P","seed":16}]
	,[{"name":"Q","id":"Q","seed":17},{"name":"R","id":"R","seed":18}]
	,[{"name":"S","id":"S","seed":19},{"name":"T","id":"T","seed":20}]
	,[{"name":"U","id":"U","seed":21},{"name":"V","id":"V","seed":22}]
	,[{"name":"W","id":"W","seed":23},{"name":"X","id":"X","seed":24}]
	,[{"name":"Y","id":"Y","seed":25},{"name":"Z","id":"Z","seed":26}]
	,[{"name":"AA","id":"AA","seed":27},{"name":"BB","id":"BB","seed":28}]
	,[{"name":"CC","id":"CC","seed":29},{"name":"DD","id":"DD","seed":30}]
	,[{"name":"EE","id":"EE","seed":31},{"name":"FF","id":"FF","seed":32}]]
	
	
	,[[{"name":"A","id":"A","seed":1},{"name":"C","id":"C","seed":3}]
	,[{"name":"E","id":"E","seed":5},{"name":"G","id":"G","seed":7}]
	,[{"name":"I","id":"I","seed":9},{"name":"K","id":"K","seed":11}]
	,[{"name":"M","id":"M","seed":13},{"name":"O","id":"O","seed":15}]
	,[{"name":"Q","id":"Q","seed":17},{"name":"S","id":"S","seed":19}]
	,[{"name":"U","id":"U","seed":21},{"name":"W","id":"W","seed":23}]
	,[{"name":"Y","id":"Y","seed":25},{"name":"AA","id":"AA","seed":27}]
	,[{"name":"CC","id":"CC","seed":29},{"name":"EE","id":"EE","seed":31}]]
	
	,[[{"name":"A","id":"A","seed":1},{"name":"E","id":"E","seed":5}]
	,[{"name":"I","id":"I","seed":21},{"name":"M","id":"M","seed":13}]
	,[{"name":"Q","id":"Q","seed":17},{"name":"U","id":"U","seed":21}]
	,[{"name":"Y","id":"Y","seed":25},{"name":"CC","id":"CC","seed":29}]]
	
	,[[{"name":"A","id":"A","seed":1},{"name":"I","id":"I","seed":21}]
	,[{"name":"Q","id":"Q","seed":17},{"name":"Y","id":"Y","seed":25}]]
	
	,[[{"name" : "A", "id" : "A", "seed" : 1} ],[ {"name" : "Q", "id" : "Q", "seed" : 17}]],
	
	[[ {"name" : "A", "id" : "A", "seed" : 1} ]]
]
Thanks for your help.
